[1.155s] Traceback (most recent call last):
  File "/home/i880/anaconda3/lib/python3.11/site-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i880/anaconda3/lib/python3.11/site-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i880/anaconda3/lib/python3.11/site-packages/colcon_ros/task/ament_python/build.py", line 102, in build
    return await extension.build(additional_hooks=additional_hooks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i880/anaconda3/lib/python3.11/site-packages/colcon_core/task/python/build.py", line 96, in build
    available_commands = await self._get_available_commands(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i880/anaconda3/lib/python3.11/site-packages/colcon_core/task/python/build.py", line 194, in _get_available_commands
    output = await check_output(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/i880/anaconda3/lib/python3.11/site-packages/colcon_core/subprocess.py", line 129, in check_output
    assert not rc, f'Expected {args} to pass: {stderr_data}'
AssertionError: Expected ['/home/i880/anaconda3/bin/python', '-W', 'ignore:setup.py install is deprecated', '-W', 'ignore:easy_install command is deprecated', 'setup.py', '--help-commands'] to pass: Traceback (most recent call last):
  File "/home/i880/programming/ros2/object_detection_ros2/setup.py", line 6, in <module>
    setup(
  File "/home/i880/anaconda3/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i880/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 172, in setup
    ok = dist.parse_command_line()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i880/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 472, in parse_command_line
    if self.handle_display_options(option_order):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i880/anaconda3/lib/python3.11/site-packages/setuptools/dist.py", line 965, in handle_display_options
    return _Distribution.handle_display_options(self, option_order)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i880/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 686, in handle_display_options
    self.print_commands()
  File "/home/i880/anaconda3/lib/python3.11/site-packages/setuptools/dist.py", line 744, in print_commands
    cmdclass = ep.load()
               ^^^^^^^^^
  File "/home/i880/anaconda3/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i880/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/i880/anaconda3/lib/python3.11/site-packages/conda_build/bdist_conda.py", line 11, in <module>
    from . import api
  File "/home/i880/anaconda3/lib/python3.11/site-packages/conda_build/api.py", line 21, in <module>
    from .config import DEFAULT_PREFIX_LENGTH as _prefix_length
  File "/home/i880/anaconda3/lib/python3.11/site-packages/conda_build/config.py", line 18, in <module>
    from .conda_interface import (
  File "/home/i880/anaconda3/lib/python3.11/site-packages/conda_build/conda_interface.py", line 11, in <module>
    from conda.auxlib.packaging import (  # noqa: F401
ModuleNotFoundError: No module named 'conda.auxlib.packaging'

